### PR TITLE
add wip tutorial on correlated random effects

### PR DESCRIPTION
**Pull request by hansvancalster**
Not sure if this will make it as a tutorial, but anyway I copied it from the rpubs repo. 

So this is a WIP.

@ThierryO for the moment it is just R code. In order to make it into a tutorial some explanation is necessary.
Also, the code reads a rather large csv file, which I have not committed. I leave it up to you on how/ if to proceed with this tutorial.

### CODE REVIEW

**Comment by hansvancalster** [comment]
@ThierryO please wait working on this. I think I missed some information that was available. Will fix this later.

**Comment by hansvancalster** [comment]
@ThierryO the tutorial is now up to date with what is available on Rpubs. Do I add the 10Mb csv to the repo (I am OK with this)?

**Comment by florisvdh** [comment]
I use Git LFS for large files, or other solutions like the `googledrive` package (`drive_download(as_id("a24dcf534bsU389"), path = file.path(tempdir(), "large-file.csv")`). Git LFS however nicely integrates with git versioning when the large files evolve too. It is to be installed separately, see https://git-lfs.github.com.

```bash
# After a file is set to track with LFS,
# you can use regular git status, add, commit, checkout. 
# Seen from the working directory, these will behave
# as if the file were stored as normal in the git repo.
# In the background, LFS files are stored separately
# and a simple placeholder is stored in the repo
# itself (visible e.g. with 'git diff', 'git show' or in the remote).
 
git lfs track large-file.csv
git add .gitattributes  # where the LFS tracking is defined
git add large-file.csv
git commit -m "Added csv file (LFS)"
# have made changes to the csv along with other things?
git add large-file.csv index.Rmd index.md
git commit -m "Changed csv file and tutorial"

# For LFS-files -AFAIK- pushing currently still needs to be done 
# in a separate fashion beforehand

git lfs push origin tutorial-branch # first upload LFS files for separate storage
git push                            # regular push of commits
# But, according to the website this two-step approach
# isn't needed anymore :-)
```

**Comment by hansvancalster** [comment]
@florisvdh Cool! So LFS has come to GitHub for free now. That is new. 
But, in this case in my opinion it is better to just push the 10 Mb csv file because it is not "large" and not a "binary" file and will probably never change during its lifetime on this repo. I was just hesitant to do so on a repo which I do not manage. In other repo's we have many of such < 50 Mb csv files tracked without a problem.
 Do you agree?

**Comment by florisvdh** [comment]
> Do you agree?

I have no strong opinion on this - sure you can go with this, and it's not the first large file in this repo. It's rather my preference to keep git repositories small - to me 'small' is like simple and brilliant.

Thanks for pointing to the interesting thread in #181 BTW.

I know one tool ([QGit](https://github.com/tibirna/qgit)) that, when not customized at startup, does suffer from the presence of multi-mega-byte files that have changed in the repo, when it loads the repo history, but that's probably a consequence of the git commands that it runs :wink:.

Current master of the tutorials repo already has quite a lot of somewhat larger binary files, see below, which poses no problems. But truly clean? :thinking: 

<details>

<summary><strong>Files larger than 100 kB in the master branch (b34d6c0)</strong></summary>

```bash
ls -S1sh $(find . -type f -size +100k -not -path "./.git/*")
2,0M ./content/tutorials/r_inla/spatial.pdf
1,8M ./content/tutorials/r_beginners/data/20180123_rainfall_klemskerke.csv
1,4M ./content/tutorials/r_beginners/data/bosvitaliteit.accdb
1,2M ./content/tutorials/r_beginners/src/Rmarkdown_oefening_resultaat.html
1,2M ./content/tutorials/r_effectclass/effectclass.pdf
792K ./content/tutorials/r_beginners/src/R_en_RStudio.pdf
756K ./content/tutorials/r_beginners/src/ggplot.pdf
712K ./content/tutorials/r_tidyverse_piping/images/chiphooray.png
692K ./content/tutorials/r_effectclass/effectclass/photo-of-forest-with-fog-1671324.jpg
680K ./content/tutorials/r_inla/random_intercept.pdf
656K ./content/tutorials/spatial_create_leaflet_map/index_files/figure-markdown_github/unnamed-chunk-6-1.png
588K ./content/tutorials/spatial_transform_crs/index_files/figure-markdown_github/unnamed-chunk-5-1.png
556K ./content/tutorials/spatial_point_in_polygon/index_files/figure-markdown_github/unnamed-chunk-16-1.png
556K ./content/tutorials/spatial_point_in_polygon/index_files/figure-markdown_github/unnamed-chunk-18-1.png
544K ./content/tutorials/r_beginners/src/dplyr.pdf
532K ./content/tutorials/r_inla/inlabru.pdf
460K ./content/tutorials/r_beginners/src/Rmarkdown.pdf
372K ./content/tutorials/r_inla/random_intercept/pexels-photo-167698.jpeg
372K ./content/tutorials/spatial_wms_services/index_files/figure-markdown_github/unnamed-chunk-4-1.png
356K ./content/tutorials/r_inla/spatial/aerial-aerial-shot-aerial-view-753868.jpg
300K ./content/tutorials/r_inla/inlabru/pexels-photo-1310755.jpeg
280K ./content/tutorials/r_beginners/Figuren/iris-machinelearning.png
256K ./content/tutorials/r_beginners/src/data_inlezen.pdf
252K ./content/tutorials/r_beginners/Figuren/InterfaceRStudio.jpg
240K ./content/tutorials/r_beginners/src/dplyr_huistaak.pdf
216K ./content/tutorials/spatial_wms_services/index_files/figure-markdown_github/unnamed-chunk-6-1.png
204K ./content/tutorials/r_database_access/database-R/access_dsn.png
184K ./content/tutorials/r_beginners/src/data_inlezen_ggplot_huistaak.pdf
176K ./content/tutorials/r_tidyverse_piping/images/hooraypenguin.jpg
176K ./content/tutorials/r_beginners/src/R_en_RStudio_huistaak.pdf
168K ./content/tutorials/spatial_wms_services/index_files/figure-markdown_github/unnamed-chunk-7-1.png
148K ./content/tutorials/r_beginners/src/Rmarkdown_huistaak.pdf
148K ./content/tutorials/r_beginners/src/dplyr_oefening.pdf
144K ./content/tutorials/r_beginners/Figuren/gather_data_R.png
140K ./content/tutorials/r_beginners/src/ggplot_oefening.pdf
136K ./content/tutorials/r_beginners/Figuren/spread_data_R.png
132K ./content/tutorials/r_beginners/Figuren/rstudio_script.png
112K ./content/tutorials/r_beginners/src/data_inlezen_oefening.pdf
```

</details>

**Comment by hansvancalster** [comment]
Let me try out lfs on this file then :wink:  I wonder what happens when someone wants to make changes to that file and does not have lfs installed.

**Comment by hansvancalster** [comment]
@florisvdh thanks for pointing to LFS. This worked wonderfully. I also learned that the file is now stored on a different server and the repo only contains a pointer to the file on that server. A very nice solution for large files, which, as it happens, I am going to need a lot in a different project. :rocket:

**Comment by florisvdh** [comment]
:tada: :+1: 

Indeed, it appears such files are stored at https://media.githubusercontent.com/. I remember they may be storage limits (compared to gitlab.com), but that may have changed.

> I wonder what happens when someone wants to make changes to that file and does not have lfs installed.

I guess it will result in having the pointer file only - AFAIK git itself is unaware of Git LFS. If I remember correctly, with Git LFS it's only when checking out something that a certain file at a certain version is downloaded from a server to the user's working directory (that would also make it convenient in managing local storage).

My first time _collaborating_ with LFS (note the third last line) :smiley: :

```bash
$ git fetch 
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 68 (delta 38), reused 61 (delta 34), pack-reused 0
Unpacking objects: 100% (68/68), done.
From https://github.com/inbo/tutorials
   b34d6c0..e75720a  master     -> origin/master
   6cbd600..7a7a6ed  gh-pages   -> origin/gh-pages
   8a23bca..0f5f511  rpubs-correlated-re -> origin/rpubs-correlated-re
   44dbd81..a25e567  rpubs-olre -> origin/rpubs-olre
 * [new branch]      softw-inbodb -> origin/softw-inbodb
$ git checkout --track origin/rpubs-correlated-re 
Downloading content/tutorials/r_perfect_correlation/correlated-random-effects.csv (11 MB)
Branch rpubs-correlated-re set up to track remote branch rpubs-correlated-re from origin.
Switched to a new branch 'rpubs-correlated-re'
```

**Comment by damianooldoni** [comment]
@hansvancalster @ThierryO and I decided to close this PR as it is not releveant anymore.
Reason: this tutorial is already online. Who searches for it, will find it.

**Pull request closed without merging**
