### PR TITLE
Overview of INBO packages

### PR DESCRIPTION
**Pull request by florisvdh**
This PR proposes a commented list of INBO packages ('article' format); this targets issue #93.

[Attached](https://github.com/inbo/tutorials/files/3012243/index.html.zip) is a locally generated html to aid in reviewing.

Several package authors are among the reviewers -- please add those that I may have forgotten unintentionally.

This may (hopefully) be an interesting post to point at when communicating about new features in this website, so please have a careful look. I suggest that you propose your enhancements in a PR relative to this `inbo_packages` branch.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
Nice work! I really like the division in research stage.

**Comment by ElsLommelen** [comment]
I would like to add the [LSVI package](https://github.com/inbo/LSVI) as well, but I am not sure where it fits in.  It could be added to study design or retrieve data (which data do we need to evaluate habitat quality?) and it could be added to data analysis, but it is nor graphs neither models (rather: automatisation of calculations).

**Comment by ElsLommelen** [comment]
Regarding from the viewpoint of a user: wouldn't it give a better overview if packages were ordered in functional groups and **for instance** separated between 
- technical packages (e.g. get2rdata, inboutils),
- statistical packages (e.g. grts, inlatools, multimput,...),
- data retrieving packages (e.g. wateRinfo, pydov, pyinaturalist,...),
- packages on specific ecological topics (e.g. niche_vlaanderen,...) and
- INBO styles (INBOtheme, INBOmd)?

To me the subdivision in different research stages feels a little strange: I would for instance rather expect INBOtheme in Publish than in Analyze data, and niche_vlaanderen could maybe already be useful in the design stage?

**Comment by florisvdh** [comment]
@ElsLommelen thank you for your ideas! A bit of feedback:

- `LSVI`: would probably fit into an extra subcategory of 'Analyze data' (evaluations / indices or such)
- `INBOtheme` may fit better into 'Publish' indeed, I was a bit in doubt. I'll push an update.
- perhaps another classification can be followed -- I'll await other responses.
  - if we leave the research stages, it is still an option to add a table that marks which packages are useful to which research stages. Some may indeed relate to more than one research stage, however I feel that most of them have a major focus on one stage.
  - personally I see potential confusion between 'technical packages' and all other categories, and between 'ecological' and 'data retrieving'. Not convinced yet ;-)

**Comment by stijnvanhoey** [comment]
as mentioned before, +1 for the research stages division ;-)

**Comment by florisvdh** [comment]
I propose to merge this PR in the course of this week. Your feedback is still welcome. [Here](https://github.com/inbo/tutorials/files/3106489/index.html.zip) is an updated html version.

**Pull request merged**
