### PR TITLE
Remove artifacts on a daily base

### PR DESCRIPTION
**Pull request by ThierryO**
Keep only the most recent artifact.

Solves #251

### CODE REVIEW

**Comment by peterdesmet** [comment]
Nice. Artefacts in the repo are website previews for review. Since reviews don't always happen the same day, I would keep them around for longer. 14 days?

**Comment by ThierryO** [comment]
Note that we only remove an artifact when it is both older than a day and not one of the most `x` recent artifacts. I'd rather increase the number of recent artifacts to keep than to keep all artifacts for a longer period.

**Comment by peterdesmet** [comment]
Fair enough, but a stale PR will have its artefacts removed then by a recent one with many commits.

**Review by peterdesmet — APPROVED** [review]

**Comment by ThierryO** [comment]
The ideal solution would be to keep only the artifacts related to the HEAD of each branch not merged into the main branch and not older than x days. AFAIK the artifacts don't contain information on the commit that created them.

**Pull request merged**
