### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by niconoe**
minor tweak - only to test the PR WORKFLOW

### CODE REVIEW

**Comment by niconoe** [comment]
=> great, I can now see the change (submitted by PR) in the artifact file (see link above). I will now try to add one more commit to this PR and check it gets triggered again!

**Comment by niconoe** [comment]
=> that works (artifact gets updated to reflect latest change)

**Comment by florisvdh** [comment]
Coool!! 

@niconoe does the artikfact-website render well on your PC? I believe its hyperlinks are hardcoded relative to root? With **hugo** one can pass `-b` to change base directory, but not clear to me how to make it work in a directory-independent (relative?) way.

**Comment by niconoe** [comment]
indeed, I can see the issue too! Will revisit soon, then :)

**Pull request closed without merging**
