### PR TITLE
add package dhcurve to inbo_software (issue #183)

### PR DESCRIPTION
**Pull request by ElsLommelen**
## Description
I added a link and a description of package dhcurve to the webpage of INBO software.
Package is in collaboration with @ThierryO and @leymanan

## Related Issue
Part of #183

## Task list

- [x] My tutorial or article is placed in a subfolder of `tutorials/content`
- [x] The filename of my tutorial or article is `index.md`. In case of an Rmarkdown tutorial I have knitted my `index.Rmd` to `index.md` (both files are pushed to the repo). 
- [x] I have included `tags` in the YAML header (see the tags listed in the [tutorials website side bar](https://inbo.github.io/tutorials/) for tags that have been used before)
- [x] I have added `categories` to the YAML header and my category tags are from the [list of category tags](https://github.com/inbo/tutorials/blob/master/static/list_of_categories)

## Previewing the pull request

Thanks to GitHub Actions, an artifact (=zip file) of the rendered website is automatically created for each pull request.

### Instructions

1) On the PR page, you can find a "details" link under "checks - On PR, build the site and ...". Go there, click on the top link in the left sidebar ("Summary"), and download the generated artifact at the bottom of the page.
2) Decompress it and make sure the target directory is called 'tutorials' (you may need to rename it)
3) From the parent directory (just above the `tutorials` folder you created/renamed), run `python -m http.server 8887`, _or_ launch the Google Chrome [Web Server app](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb) and point it at the parent directory.
4) Point your browser to http://localhost:8887/tutorials.
5) Review the updated website and accept/refuse/comment the PR

**Note: for step 3, you can use any other simple HTTP server to serve the current directory if you don't have a Python 3 environment or Google Chrome available.**

### CODE REVIEW

**Comment by ThierryO** [comment]
Maybe at the package to https://github.com/inbo/universe too.

**Review by ThierryO — APPROVED** [review]

**Comment by florisvdh** [comment]
@ElsLommelen For now (perhaps awaiting #261 before merging): can you merge `master` in `add-dhcurve` (`git checkout add-dhcurve && git merge --no-ff master`) and push the new commit? That could solve the failed check; the `add-dhcurve` branch is relatively old.

**Comment by ElsLommelen** [comment]
@florisvdh oups, I did this locally before making this PR, but I forgot to push the commits... :-(

**Comment by florisvdh** [comment]
Excellent, thanks.

**Comment by peterdesmet** [comment]
This can be merged. I'll resolve conflicts in #261.

**Pull request merged**
