### PR TITLE
Start styleguide for repositories

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by peterdesmet** [comment]
I've moved the file one directory lower, so it's also in the `source` directory (see #5)

**Comment by ThierryO** [comment]
Should we add a style-guide for R code as well? I tend to test the coding style in my packages with the `lintr` package. You can use it for checking code in R files as well. E.g. ` lintr::lint("source/render-Rmd.R")` or `lintr::lint("source/installation/R_admin.Rmd")`

See https://github.com/jimhester/lintr for the available linters.

**Comment by peterdesmet** [comment]
Uppercase R: see f00ab523476177010257678a61ecaa40d2e062d3

**Comment by peterdesmet** [comment]
styleguide for R:

* Yes!
* Name and place it in: development/styleguide-R.Rmd

**Comment by peterdesmet** [comment]
Will update file to .Rmd if everyone agrees to only use that format.

**Comment by peterdesmet** [comment]
Updated file to .Rmd @stijnvanhoey or @ThierryO can you review?

**Pull request merged**
