### PR TITLE
Gsheet

### PR DESCRIPTION
**Pull request by stijnvanhoey**

### CODE REVIEW

**Comment by peterdesmet** [comment]
Do we plan to create an index of all files in the README?

**Comment by stijnvanhoey** [comment]
When I add the github_document as output and render (`rmarkdown::render("googlesheet-R.Rmd", output_dir = "../../output/data-handling/")`, I get two unwanted elements:
* the figure path names are defined as absolute paths 
* an html file is made as well, even though I did not put this in the output profile or add it to the options

Any help?

**Comment by ThierryO** [comment]
I've solved the html problem by adding *.html to .gitignore. I'll look into the figure paths.

**Comment by stijnvanhoey** [comment]
@ThierryO  great improvement, thanks!

**Comment by ThierryO** [comment]
`rmarkdown::render()` calls `normalizePath()` which returns the canonical form of the path. Which is an absolute path (no ./, ../ nor symbolic links). The HTML doesn't have that problem because the image is stored within the HTML

**Comment by ThierryO** [comment]
The list of available googlesheets will depend on the user that runs the code. Maybe we should use a demo gmail account to illustrate this. Then we can get the same results regardless of who runs the code.

**Pull request merged**
