### PR TITLE
Tutorial SQLserver querying with DBI

### PR DESCRIPTION
**Pull request by florisvdh**
PR is relative to theme-update branch.

### CODE REVIEW

**Comment by florisvdh** [comment]
I think it would be a good idea to extend the tutorial with the dplyr syntax approach. See [here](https://db.rstudio.com/getting-started/database-queries#query-using-dplyr-syntax). But it may have its own limitations, I have no experience yet. If that works well for our usecases, it may become our advised (tidyverse) approach.

**Comment by peterdesmet** [comment]
I have tried dplyr functions (obfuscating SQL) and direct SQL to interact with a database (gull tracking data) from R. I found direct SQL to be faster and much more customizable. Imo learning some basic SQL skills will lead to less frustration than to query a database with dplyr.

**Comment by stijnvanhoey** [comment]
Thanks for the improvements. I would leave the dplyr-syntax way of working to a separate tutorial instead of integrating too much information in a single tutorial. @florisvdh can you knit local to a `md` file and push that one as well? As discussed, the new setup will only use the `md` file for the website and knitting is done locally. Thanks

**Comment by florisvdh** [comment]
Sounds fine @stijnvanhoey. Thanks @peterdesmet to share the experience. Perhaps we should explicitly add this experience in both tutorials.

I've edited `index.md` manually, hmmpf, as I could not run the chunks from home.

**Comment by stijnvanhoey** [comment]
Thanks a lot @florisvdh

**Pull request merged**
