### PR TITLE
Split source

### PR DESCRIPTION
**Pull request by ThierryO**
Here is a possible solution to split the source files and the output. Storing the rendered document makes it easier for the end user to read the document. Note that note all end user are whizzkids who can understand the code without seeing the rendered result.

### CODE REVIEW

**Comment by peterdesmet** [comment]
Good start, but:

* Use underscore for all files, including R-user.md, R-admin.Rmd
* Include all source files in /source, so also R-user.md. We want one folder with all source files and only edit there!
* Add a source/files and put `Rprofile.site` there
* Render all output to an /output folder. It is then the sibling folder of /source.

**Comment by ThierryO** [comment]
Should we place files like `Rprofile.site` twice? Or place a link to them in the md?

**Comment by ThierryO** [comment]
In case we want the md files in source as well, I'd suggest to use only Rmd files. That makes the rendering less complicated.

**Comment by peterdesmet** [comment]
@ThierryO good question, these are things that are solved by e.g. a Pelican static renderer. The idea is to never manually touch /output.

**Comment by peterdesmet** [comment]
@ThierryO, I'm fine with only using .Rmd files. That also solves how to add metadata to the top (which is e.g. missing for https://github.com/inbo/tutorials/blob/style-guide/source/development/styleguide-repos.md)

**Comment by ThierryO** [comment]
I've updated the files to match the style guide

**Comment by peterdesmet** [comment]
I haven't been able to render the file yet (I'm new to Rstudio)

**Comment by ThierryO** [comment]
Do we want the name of the maintainer to be displayed on the rendered document? If we do, must use the author tag (maybe in combination with the maintainer tag). Tags which are not know by render functions are usually silently ignored.

**Comment by ThierryO** [comment]
I've added instructions to compile the Rmd files and to install and setup RStudio

**Pull request merged**
