### PR TITLE
update WFS tutorial Geometry column names Fixes issue #304

### LINKED ISSUE #304: WFS services in R: small suggestion for example 5
Small suggestion for 'Example 5: extract feature data at particular points':

> CQL_FILTER: Define the spatial operator, in this case `INTERSECTS` of the WFS `geom` and our `POINT` coordinate. The operators are enlisted in the `<ogc:SpatialOperators>` field.

It might seem obvious to you, but since it was not for me: I think it might be useful to add sthing like this: 

> `geom` is the name of the geometry field (in this example `geom` but other web services use `SHAPE`  (maybe add here the most common examples))

I thought  `geom` was some kind of reserved name...

### PR DESCRIPTION
**Pull request by hansvancalster**
## Description

See #304

## Related Issue

closes #304

## Task list

- [x] My tutorial or article is placed in a subfolder of `tutorials/content`
- [x] The filename of my tutorial or article is `index.md`. In case of an Rmarkdown tutorial I have knitted my `index.Rmd` to `index.md` (both files are pushed to the repo). 
- [x] I have included `tags` in the YAML header (see the tags listed in the [tutorials website side bar](https://inbo.github.io/tutorials/) for tags that have been used before)
- [x] I have added `categories` to the YAML header and my category tags are from the [list of category tags](https://github.com/inbo/tutorials/blob/master/static/list_of_categories)

## Previewing the pull request

Thanks to GitHub Actions, an artifact (=zip file) of the rendered website is automatically created for each pull request.

### Instructions

1) On the PR page, you can find a "details" link under "checks - On PR, build the site and ...". Go there, click on the top link in the left sidebar ("Summary"), and download the generated artifact at the bottom of the page.
2) Decompress it and make sure the target directory is called 'tutorials' (you may need to rename it)
3) From the parent directory (just above the `tutorials` folder you created/renamed), run `python -m http.server 8887`, _or_ launch the Google Chrome [Web Server app](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb) and point it at the parent directory.
4) Point your browser to http://localhost:8887/tutorials.
5) Review the updated website and accept/refuse/comment the PR

**Note: for step 3, you can use any other simple HTTP server to serve the current directory if you don't have a Python 3 environment or Google Chrome available.**

### CODE REVIEW

**Comment by hansvancalster** [comment]
Note that a lot more changes were introduced due to updated packages / updated dates and WFS responses. The actual relevant change is in example 5.

**Review by cecileherr — APPROVED** [review]
Thanks for the quick reaction :-) (note that I haven't reviewed the other changes)

**Review by florisvdh — APPROVED** [review]
Thanks for the issue and the solution!

It appears that the below referred URL (didactical explanation on CQL) is dead:

https://github.com/inbo/tutorials/blob/f6faaeb7cb815cff43eb3f60ab2ed444dba4031a/content/tutorials/spatial_wfs_services/index.Rmd#L262

@hansvancalster do you have an alternative? One (older) possibility is http://zing.z3950.org/cql/intro.html (referred by Wikipedia), but unofficial documentation/tutorials seem scarce.

BTW the latter adds to #170.

**Comment by hansvancalster** [comment]
> @hansvancalster do you have an alternative? One (older) possibility is http://zing.z3950.org/cql/intro.html (referred by Wikipedia), but unofficial documentation/tutorials seem scarce.

See [2810203](https://github.com/inbo/tutorials/pull/305/commits/2810203052c1f341613a19e8d6ab20b8552b44d0)
it seems official documentation for CQL is currently being drafted (will become an OGC standard)

**Pull request merged**
