### PR TITLE
Add rgbif to INBO software

### PR DESCRIPTION
**Pull request by damianooldoni**
I am one of the [authors](https://docs.ropensci.org/rgbif/authors.html)

### CODE REVIEW

**Review by florisvdh — CHANGES_REQUESTED** [review]
Excellent idea @damianooldoni :+1: . Please, also add an entry under 'Biological data' with a very short characterization. (Perhaps from the DESCRIPTION file).

**Review by hansvancalster — COMMENTED** [review]
Good addition! Indeed, just need to add the short description.

**Comment by damianooldoni** [comment]
@florisvdh, @hansvancalster : thanks for noticing it! I added a brief description in ba79d58.  
I hope you can turn :red_circle:  to :green_circle: for this PR. Then I will merge it.

**Review by hansvancalster — APPROVED** [review]

**Review by florisvdh — APPROVED** [review]
:+1:

**Pull request merged**
