### PR TITLE
Update index.Rmd

### PR DESCRIPTION
**Pull request by Fred-VLIZ**
fix: typo

### CODE REVIEW

**Review by hansvancalster — APPROVED** [review]
Thanks @Fred-VLIZ :+1:

**Comment by hansvancalster** [comment]
Ah I see the `index.md` needs updating as well. @Fred-VLIZ can you make and commit the same change also in the `index.md` file on your fork of the repo and push the change?

**Comment by Fred-VLIZ** [comment]
@hansvancalster - done! :)

**Comment by hansvancalster** [comment]
@Fred-VLIZ I think you still need to commit/Push? (I don't see a new commit in this PR)

**Comment by hansvancalster** [comment]
Too fast again - I see it's done in PR #194. Thanks!

**Pull request merged**
